#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qwt
Version  : 6.1.3
Release  : 1
URL      : https://downloads.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2
Source0  : https://downloads.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: qwt-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Designer)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)

%description
The Qwt Widget Library
----------------------
Qwt is an extension to the libraries of the Qt Project.

%package license
Summary: license components for the qwt package.
Group: Default

%description license
license components for the qwt package.


%prep
%setup -q -n qwt-6.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1545361678
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qwt
cp COPYING %{buildroot}/usr/share/package-licenses/qwt/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qwt/COPYING
